version: "3.9"
services:

  sm-app-php-base:
    build:
      dockerfile: Dockerfile-Base
      context: ./docker/php
    image: ${APPLICATION_PHP_BASE_IMAGE_NAME}:${APPLICATION_PHP_BASE_IMAGE_TAG}

  sm-app-php-fpm:
    build:
      dockerfile: Dockerfile-Final
      context: ./docker/php
      target: ${APPLICATION_PHP_FPM_CONTAINER_NAME}
      args:
        APPLICATION_ROOT_DIR: ${APPLICATION_ROOT_DIR}
    image: ${APPLICATION_PHP_FPM_IMAGE_NAME}:${APPLICATION_PHP_FPM_IMAGE_TAG}

  sm-app-web:
    build:
      context: ./docker/nginx
      target: ${APPLICATION_WEB_SERVER_CONTAINER_NAME}
    image: ${APPLICATION_WEB_SERVER_IMAGE_NAME}:${APPLICATION_WEB_SERVER_IMAGE_TAG}
